-- ============================================================
-- StayEase Hotel Booking System
-- queries.sql
-- Collection of SQL queries demonstrating DBMS concepts
-- ============================================================

USE stayease;

-- ============================================================
-- Query 1 : Display all hotels
-- ============================================================

SELECT * FROM hotels;

-- ============================================================
-- Query 2 : Display all users
-- ============================================================

SELECT * FROM users;

-- ============================================================
-- Query 3 : Display available rooms
-- ============================================================

SELECT *
FROM rooms
WHERE status='available';

-- ============================================================
-- Query 4 : Hotels with rating >= 4.8
-- ============================================================

SELECT hotel_name, star_rating
FROM hotels
WHERE star_rating>=4.8;

-- ============================================================
-- Query 5 : Rooms costing more than ₹5000
-- ============================================================

SELECT room_number,price
FROM rooms
WHERE price>5000;

-- ============================================================
-- Query 6 : Hotels sorted by rating
-- ============================================================

SELECT hotel_name,star_rating
FROM hotels
ORDER BY star_rating DESC;

-- ============================================================
-- Query 7 : Number of hotels in every city
-- ============================================================

SELECT
c.city_name,
COUNT(h.hotel_id) AS total_hotels
FROM cities c
LEFT JOIN hotels h
ON c.city_id=h.city_id
GROUP BY c.city_name;

-- ============================================================
-- Query 8 : Average room price in each hotel
-- ============================================================

SELECT
h.hotel_name,
AVG(r.price) AS average_price
FROM hotels h
JOIN rooms r
ON h.hotel_id=r.hotel_id
GROUP BY h.hotel_name;

-- ============================================================
-- Query 9 : Maximum room price of every hotel
-- ============================================================

SELECT
h.hotel_name,
MAX(r.price) AS highest_price
FROM hotels h
JOIN rooms r
ON h.hotel_id=r.hotel_id
GROUP BY h.hotel_name;

-- ============================================================
-- Query 10 : Hotels having more than one room
-- ============================================================

SELECT
hotel_id,
COUNT(room_id) AS total_rooms
FROM rooms
GROUP BY hotel_id
HAVING COUNT(room_id)>1;

-- ============================================================
-- Query 11 : User booking details
-- ============================================================

SELECT
u.full_name,
b.booking_id,
b.check_in,
b.check_out,
b.booking_status
FROM users u
JOIN bookings b
ON u.user_id=b.user_id;

-- ============================================================
-- Query 12 : Hotel and City Details
-- ============================================================

SELECT
h.hotel_name,
c.city_name
FROM hotels h
JOIN cities c
ON h.city_id=c.city_id;

-- ============================================================
-- Query 13 : Room with Hotel Name
-- ============================================================

SELECT
h.hotel_name,
r.room_number,
r.price
FROM hotels h
JOIN rooms r
ON h.hotel_id=r.hotel_id;

-- ============================================================
-- Query 14 : Booking with Payment Details
-- ============================================================

SELECT
b.booking_id,
u.full_name,
p.amount,
p.payment_status
FROM bookings b
JOIN users u
ON b.user_id=u.user_id
JOIN payments p
ON b.booking_id=p.booking_id;

-- ============================================================
-- Query 15 : Hotel Reviews
-- ============================================================

SELECT
u.full_name,
h.hotel_name,
r.rating,
r.comment
FROM reviews r
JOIN users u
ON r.user_id=u.user_id
JOIN hotels h
ON r.hotel_id=h.hotel_id;

-- ============================================================
-- Query 16 : Number of bookings made by each user
-- ============================================================

SELECT
u.full_name,
COUNT(b.booking_id) AS total_bookings
FROM users u
LEFT JOIN bookings b
ON u.user_id=b.user_id
GROUP BY u.full_name;

-- ============================================================
-- Query 17 : Revenue generated by each hotel
-- ============================================================

SELECT
h.hotel_name,
SUM(b.total_amount) AS revenue
FROM hotels h
JOIN rooms r
ON h.hotel_id=r.hotel_id
JOIN bookings b
ON r.room_id=b.room_id
GROUP BY h.hotel_name;

-- ============================================================
-- Query 18 : Hotels having average room price greater than 6000
-- ============================================================

SELECT
h.hotel_name,
AVG(r.price) AS avg_price
FROM hotels h
JOIN rooms r
ON h.hotel_id=r.hotel_id
GROUP BY h.hotel_name
HAVING AVG(r.price)>6000;

-- ============================================================
-- Query 19 : Find the most expensive room
-- ============================================================

SELECT *
FROM rooms
WHERE price=
(
SELECT MAX(price)
FROM rooms
);

-- ============================================================
-- Query 20 : Users who have completed bookings
-- ============================================================

SELECT DISTINCT
u.full_name
FROM users u
JOIN bookings b
ON u.user_id=b.user_id
WHERE b.booking_status='completed';

-- ============================================================
-- Query 21 : Hotels that provide Swimming Pool
-- ============================================================

SELECT
h.hotel_name
FROM hotels h
JOIN hotel_amenities ha
ON h.hotel_id=ha.hotel_id
JOIN amenities a
ON ha.amenity_id=a.amenity_id
WHERE a.amenity_name='Swimming Pool';

-- ============================================================
-- Query 22 : Number of amenities provided by every hotel
-- ============================================================

SELECT
h.hotel_name,
COUNT(ha.amenity_id) AS total_amenities
FROM hotels h
JOIN hotel_amenities ha
ON h.hotel_id=ha.hotel_id
GROUP BY h.hotel_name;

-- ============================================================
-- Query 23 : Rooms with their Room Type
-- ============================================================

SELECT
r.room_number,
rt.type_name,
r.price
FROM rooms r
JOIN room_types rt
ON r.room_type_id=rt.room_type_id;

-- ============================================================
-- Query 24 : Pending Payments
-- ============================================================

SELECT *
FROM payments
WHERE payment_status='pending';

-- ============================================================
-- Query 25 : Hotels that have never received a review
-- ============================================================

SELECT
hotel_name
FROM hotels
WHERE hotel_id NOT IN
(
SELECT DISTINCT hotel_id
FROM reviews
);